#!/bin/bash

set -eux

cd "${0%/*}"

# cargo build --release --features=composefs-backend

cp ../../target/release/bootc .
cp ../../target/release/bootc-initramfs-setup extra/usr/lib/dracut/modules.d/37bootc/

podman build \
    -t quay.io/fedora/fedora-bootc-bls:42 \
    -f Containerfile \
    .
